sonar.projectKey=macabre-and-mirthworks
sonar.projectName=Macabre and Mirthworks
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.jpg,**/*.jpeg,**/*.png,**/*.webp,**/*.svg,**/*.ico,**/*.otf,**/*.ttf,**/.idea/**,**/*.md
sonar.host.url=http://localhost:9000
